export const ENUM_CRUD_CHAPTER_ERRORS = {
	INVALID_FORM_DATA: "INVALID FORM DATA",
	CREATE: "CREATE CHAPTER SUCCESS",
	DELETE: "DELETE CHAPTER SUCCESS",
	NOT_FOUND: "NOT FOUND CHAPTER",
	FAILED: "FAILED CRUD CHAPTER"
} as const;

export const ENUM_REORDER_CHAPTER_ERRORS = {
	SUCCESS: "REORDER CHAPTER SUCCESS",
	ZERO_LENGTH: "NO CHAPTERS REORDER",
	FAILED: "FAILED REORDER CHAPTERS"
} as const;
