export const ENUM_CREATE_CHAPTER_ERRORS = {
	INVALID_FORM_DATA: "INVALID FORM DATA",
	SUCCESS: "CREATE CHAPTER SUCCESS",
	NOT_FOUND: "NOT FOUND CHAPTER",
	FAILED: "FAILED CREATE CHAPTER"
} as const;

export const ENUM_REORDER_CHAPTER_ERRORS = {
	SUCCESS: "REORDER CHAPTER SUCCESS",
	ZERO_LENGTH: "NO CHAPTERS REORDER",
	FAILED: "FAILED REORDER CHAPTERS"
} as const;
