export const ENUM_CRUD_COURSE_ERRORS = {
	INVALID_FORM_DATA: "INVALID FORM DATA",
	CREATE: "CREATE COURSE SUCCESS",
	ENROLL: "STRIPE ENROLLMENT SUCCESS",
	ENROLL_CREATED: "STRIPE CUSTOMER CREATED",
	ENROLL_ERROR: "STRIPE ENROLLMENT ERROR",
	ALREADY_ENROLLED: "ALREADY ENROLLED",
	DELETE: "DELETE COURSE SUCCESS",
	NOT_FOUND: "NOT FOUND COURSE",
	DUPLICATE_SLUG: "ERROR DUPLICATE SLUG",
	FAILED: "FAILED CRUD COURSE"
} as const;
