export const ENUM_CREATE_COURSE_ERRORS = {
	INVALID_FORM_DATA: "INVALID FORM DATA",
	SUCCESS: "CREATE COURSE SUCCESS",
	NOT_FOUND: "NOT FOUND COURSE",
	DUPLICATE_SLUG: "ERROR DUPLICATE SLUG",
	FAILED: "FAILED CREATE COURSE"
} as const;
