export const ENUM_CREATE_LESSON_ERRORS = {
	INVALID_FORM_DATA: "INVALID FORM DATA",
	SUCCESS: "CREATE LESSON SUCCESS",
	NOT_FOUND: "NOT FOUND LESSON",
	FAILED: "FAILED CREATE LESSON"
} as const;

export const ENUM_REORDER_LESSON_ERRORS = {
	SUCCESS: "REORDER LESSON SUCCESS",
	ZERO_LENGTH: "NO LESSONS REORDER",
	FAILED: "FAILED REORDER LESSONS"
} as const;
