export const ENUM_CRUD_LESSON_ERRORS = {
	INVALID_FORM_DATA: "INVALID FORM DATA",
	CREATE: "CREATE LESSON SUCCESS",
	DELETE: "DELETE LESSON SUCCESS",
	NOT_FOUND: "NOT FOUND LESSON",
	FAILED: "FAILED CRUD LESSON",
	MARK_COMPLETE: "MARK LESSON COMPLETE SUCCESS"
} as const;

export const ENUM_REORDER_LESSON_ERRORS = {
	SUCCESS: "REORDER LESSON SUCCESS",
	ZERO_LENGTH: "NO LESSONS REORDER",
	FAILED: "FAILED REORDER LESSONS"
} as const;
