// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
	"LocaleLayout": {
		"title": "Example App Router"
	},

	"Manifest": {
		"name": "Example App Router"
	},

	"common": {
		"buttons": {
			"back": "Back"
		},

		"upload": {
			"text": "Drop your files here or <action>click to upload</action>",
			"button": "Select",

			"error": {
				"title": "Upload Failed",
				"text": "Something went wrong",
				"button": "Retry"
			},

			"toast": {
				"manyFiles": "Too many files, please upload a maximum of 1 files.",
				"tooLarge": "File too large, please upload a file less than 5MB.",
				"presignedUrl": "Failed to generate presigned URL, please try again.",
				"upload": "File uploaded successfully"
			},

			"fields": {
				"fileName": {
					"required": "File name is required"
				},
				"contentType": {
					"required": "Content type is required"
				},
				"size": {
					"required": "File size is required"
				}
			}
		}
	},

	"LoginPage": {
		"form": {
			"title": "Welcome back!",
			"description": "Login with your GitHub Account",
			"buttons": {
				"github": "Sign with GitHub",
				"load": "Loading ...",
				"email": "Continue with email"
			},
			"or": "Or continue with",
			"signIn": {
				"success": "Signed in with GitHub, you will be redirected ...",
				"error": "Failed to sign in with GitHub, please try again later."
			},
			"signOut": {
				"success": "Signed out successfully",
				"error": "Failed to sign out, please try again later."
			}
		},
		"agreement": {
			"text": "By signing up, you agree to our <terms>Terms of Service</terms> and <privacy>Privacy Policy</privacy>."
		}
	},

	"ThemeToggle": {
		"dark": "Dark",
		"light": "Light",
		"system": "System"
	},

	"LanguageToggle": {
		"en": "🇬🇧 English",
		"ru": "🇷🇺 Russian"
	},

	"Navbar": {
		"path": {
			"main": "Home",
			"courses": "Courses",
			"dashboard": "Dashboard"
		},

		"buttons": {
			"logout": "Logout",
			"login": "Login",
			"start": "Get Started"
		}
	},

	"HomePage": {
		"badge": "The Future of Online Education",
		"title": "Elevate your Learning Experience",
		"description": "Discover a new way to learn with our modern, interactive learning management system. Take control of your learning experience, track your progress, and stay up-to-date with the latest information.",
		"buttons": {
			"explore": "Explore Courses",
			"login": "Sign In"
		},

		"keyFeatures": [
			{
				"icon": "📚",
				"title": "Comprehensive Courses",
				"description": "Access a wide range of carefully curated courses designed by industry experts."
			},
			{
				"icon": "🎮",
				"title": "Interactive Learning",
				"description": "Engage with interactive content, quizzes, and assignments to enhance your learning experience."
			},
			{
				"icon": "📊",
				"title": "Progress Tracking",
				"description": "Monitor your progress and achievements with detailed analytics and personalized dashboards."
			},
			{
				"icon": "👥",
				"title": "Community Support",
				"description": "Join a vibrant community of learners and instructors to collaborate and share knowledge."
			}
		]
	},

	"AdminCoursesPage": {
		"title": "Your Courses",
		"subtitle": "Here you can create and manage your courses.",

		"buttons": {
			"create": "Create Course"
		},

		"card": {
			"menu": {
				"edit": "Edit",
				"preview": "Preview",
				"delete": "Delete"
			},

			"buttons": {
				"edit": "Edit Course"
			}
		}
	},

	"CreateCoursePage": {
		"title": "Create Course",

		"basicInfo": {
			"title": "Basic Information",
			"description": "Provide some basic information about your course."
		}
	},

	"CourseForm": {
		"fields": {
			"title": {
				"label": "Title",
				"placeholder": "Enter course title",
				"min": "Title must be at least 3 characters",
				"max": "Title must be less than 100 characters"
			},
			"description": {
				"label": "Description",
				"placeholder": "Enter course description",
				"min": "Description must be at least 3 characters",
				"max": "Description must be less than 1000 characters"
			},
			"image": {
				"label": "File",
				"required": "File is required",
				"recommendation": "16:9 aspect ratio recommended",

				"buttons": {
					"add": "Add",
					"edit": "Edit",
					"cancel": "Cancel"
				}
			},
			"price": {
				"label": "Price (in USD)",
				"placeholder": "Enter course price",
				"min": "Price must be at least 1"
			},
			"duration": {
				"label": "Duration (in hours)",
				"placeholder": "Enter course duration",
				"min": "Duration must be at least 1 hour",
				"max": "Duration must be less than 500 hours"
			},
			"level": {
				"label": "Level",
				"placeholder": "Select course level",
				"required": "Level is required"
			},
			"category": {
				"label": "Category",
				"placeholder": "Select course category",
				"required": "Category is required"
			},
			"smallDescription": {
				"label": "Small Description",
				"placeholder": "Enter course small description",
				"min": "Small description must be at least 3 characters",
				"max": "Small description must be less than 200 characters"
			},
			"slug": {
				"label": "Slug",
				"placeholder": "Enter course slug",
				"min": "Slug must be at least 3 characters",
				"max": "Slug must be less than 100 characters"
			},
			"status": {
				"label": "Status",
				"placeholder": "Select course status",
				"required": "Status is required"
			}
		},

		"buttons": {
			"generateSlug": "Generate Slug",
			"create": "Create Course",
			"creating": "Creating ...",
			"save": "Save Course",
			"saving": "Saving"
		},

		"toast": {
			"create": {
				"success": "Course created successfully",
				"error": "ERROR: Failed to create course"
			},
			"edit": {
				"alert": "You need to make changes in the course",
				"success": "Course edited successfully",
				"error": "ERROR: Failed to edit course"
			},
			"duplicate_slug": "ERROR: Slug already exists",
			"invalid_form_data": "ERROR: Invalid form data",
			"not_found": "ERROR: Course not found"
		}
	},

	"EditCoursePage": {
		"title": "Edit Course",

		"tabs": {
			"basicInfo": "Basic Information",
			"courseStructure": "Course Structure"
		},

		"basicInfo": {
			"title": "Basic Info",
			"description": "Provide some basic information about your course."
		},

		"courseStructure": {
			"title": "Course Structure",
			"description": "Define the structure of your course.",

			"chapters": {
				"title": "Chapters",

				"buttons": {
					"new_lesson": "Create New Lesson"
				}
			}
		}
	},

	"DnDkit": {
		"toast": {
			"error": {
				"moveLesson": "ERROR: Lesson move between chapters is not allowed",
				"notFound": "ERROR: Lesson or chapter not found"
			}
		}
	}
};
export default messages;